# Generated by Django 5.0.6 on 2024-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketdetail",
            name="coin",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="marketdetail",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
