# Generated by Django 5.0.6 on 2024-06-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapApp", "0003_remove_marketdetail_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketdetail",
            old_name="id",
            new_name="job_id",
        ),
        migrations.RemoveField(
            model_name="marketdetail",
            name="coin",
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="circulating_supply",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="coin_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="contractor_address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="contractor_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="data_change",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="diluted_mc",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="market_cap",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="price",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="rank_values",
            field=models.JSONField(default=""),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="social_links",
            field=models.JSONField(default=""),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="total_supply",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="vm_ratio",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="volume",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="marketdetail",
            name="website",
            field=models.URLField(default=""),
        ),
    ]
