# Generated by Django 5.0.6 on 2024-06-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapApp", "0004_rename_id_marketdetail_job_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketdetail",
            name="rank_values",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="marketdetail",
            name="social_links",
            field=models.JSONField(default=list),
        ),
    ]
